version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo1:
    hostname: mongo1
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27017", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo2
    image: mongo:4.2.0
    ports:
      - "27117:27117"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27117", "--replSet", "rs0" ]
