version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  psql:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/psql1:/var/lib/postgresql/data
