spring:
  profiles: development
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/pm
    username: disney
    password: disney
  flyway:
    enabled: false
server:
  port: 9000
  servlet:
    context-path: /api
minDeviceId: 1
maxDeviceId: 10000000
appId: app-id-343
deviceIdPrefix: ANZ
masterUserId: ANZ-123223
wsUrl: wss://m.gl-world.de/ws
